### ISSUE TITLE
VIP portal errors are hard to get

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#84] opened 2017-03-10 09:23 UTC
The transient errors showing at the top of VIP portal:
* are not put in log files (priority 1) - Looks like some of them are put in vip.log after all...
* are not copy / paste-able (priority 2)
* disappear too quickly (priority 3)

They have two "X" buttons that ought to close them, but only the right one is working, the other one (see screen capture) does nothing... (priority 4 - cosmetics)

![errmsgbtns](https://cloud.githubusercontent.com/assets/12657074/23789524/784d3a78-057b-11e7-9dc4-ef9d0746744e.png)

**Comment by vincent-legoll** [comment] 2017-03-10 12:19
Idem with chromium

**Comment by axlbonnet** [comment] 2021-01-06 13:42
duplicate of #99

**Closed by axlbonnet** 2021-01-06 13:42 UTC
